WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GEN # 루트 노드의 세대를 1로 설정
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, GENERATION.GEN + 1 AS GEN # 다음 세대의 값 계산
    FROM ECOLI_DATA
    INNER JOIN GENERATION on GENERATION.ID = ECOLI_DATA.PARENT_ID # 현세대 노드, 부모 세대 노드 매칭 -> 자식 노드 탐색 
)

SELECT count(*) COUNT, GEN AS GENERATION
FROM GENERATION
WHERE ID NOT IN ( # 자식 있는 것들 중, NOT IN -> 자식 없음 
    SELECT PARENT_ID
    FROM GENERATION
    WHERE PARENT_ID IS NOT NULL # 자식 있음
)
GROUP BY GENERATION;